# -*- coding: utf-8 -*-
"""ip2geotool.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YZwvFv1fYBBaLRiXlpwqWQviwzPZRHTP
"""

#!pip install ip2geotools

from ip2geotools.databases.noncommercial import DbIpCity

ip = input("Enter your ip:")
response = DbIpCity.get(ip, api_key="free")

print("\n")
print("IP Address : {0}".format(response.ip_address))
print("Your Region is : {0}".format(response.region))
print("Your Country is : {0}".format(response.country))
print("Your City is : {0}".format(response.city))
print("Your longitude is : {0}".format(response.longitude))
print("Your latitude is : {0}".format(response.latitude))

dir(response)
#response.ip_address









