# -*- coding: utf-8 -*-
"""phonenumbers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sDGyZbHiWGCtchmynIicPuqfLiCt9PeB
"""

#!pip install phonenumbers

import phonenumbers
number = input("Number: ")
number = "+" + str(number)
ch_number = phonenumbers.parse(number, None)

print(ch_number)
print("State: {0}".format(geocoder.description_for_number(ch_number,"en")))
print("Valid Number: {0}".format(phonenumbers.is_valid_number(ch_number)))
print("Possible Number: {0}".format(phonenumbers.is_possible_number(ch_number)))

text = "Call me at 510-748-8230 if it's before 9:30, or on 703-4800500 after 10am."
print(text)
for match in phonenumbers.PhoneNumberMatcher(text, "US"):
  print(match)
  print(phonenumbers.format_number(match.number, phonenumbers.PhoneNumberFormat.E164))